wkeeling/selenium-wire

- seleniumwire/proxy/proxy2.py
- seleniumwire/proxy/util.py
- tests/acceptance.py
- tests/seleniumwire/proxy/test_util.py
Support for HTTP proxies with basic authentication.
> Proxy auth

- README.rst
- seleniumwire/proxy/client.py
- seleniumwire/proxy/util.py
- seleniumwire/webdriver/browser.py
With this pull request, I've added the ability to modify responses before they make their way to the browser. This allows advanced users a lot more flexibility with what they can do with `selenium-wire`
Fixes #63
I realize this may be beyond the scope of this project, but I thought I'd try anyway.
> Add ability to modify responses

- README.rst
- seleniumwire/proxy/client.py
- seleniumwire/proxy/util.py
- seleniumwire/webdriver/browser.py
> refactor custom_response_handler to inside seleniumwire_options

- seleniumwire/proxy/modifier.py
- seleniumwire/proxy/util.py
- tests/seleniumwire/proxy/test_client.py
- tests/seleniumwire/proxy/test_modifier.py
Please kindly review and suggest any changes required to get this merged
> feat: Ability to modify request headers with respect to url matching

- seleniumwire/proxy/proxy2.py
https://github.com/wkeeling/selenium-wire/issues/79
> Fix duplication of Content-Length keys when altering req or res body in ProxyRequestHandler

- NOTICES
- README.rst
- seleniumwire/proxy/modifier.py
- seleniumwire/proxy/proxy2.py
- seleniumwire/proxy/server.py
- seleniumwire/proxy/socks.py
- seleniumwire/proxy/win_inet_pton.py
- tests/acceptance.py
- tests/seleniumwire/proxy/test_proxy2.py
This PR introduces support for SOCKS proxies.
> Socks5 support

- seleniumwire/webdriver/browser.py
Implemented Remote class to allow use of `seleniumwire_options` for remote selenium connections as well.
> Implemented class for webdriver.Remote

- seleniumwire/server.py
- seleniumwire/thirdparty/mitmproxy/options.py
- seleniumwire/thirdparty/mitmproxy/server/protocol/http.py
- seleniumwire/utils.py
- tests/end2end/test_end2end.py
- tests/seleniumwire/test_server.py
- tests/seleniumwire/test_utils.py
> Fix no_proxy option

- README.rst
- seleniumwire/request.py
- seleniumwire/storage.py
- tests/seleniumwire/test_storage.py
> Make cert data available on request API

- seleniumwire/storage.py
Fixes https://github.com/wkeeling/selenium-wire/issues/248
> Index only after request saved

- README.rst
- seleniumwire/webdriver.py
> Firefox bypass localhost

- seleniumwire/thirdparty/mitmproxy/server/protocol/http.py
- tests/end2end/test_end2end.py
- tests/utils.py
> Fix bug where no_proxy is ignored for http hosts

- README.rst
> Use mitmproxy < 7.0.0

- README.rst
- seleniumwire/request.py
- seleniumwire/server.py
- seleniumwire/storage.py
- seleniumwire/utils.py
- setup.py
- tests/acceptance.py
- tests/end2end/test_end2end.py
- tests/seleniumwire/test_request.py
- tests/seleniumwire/test_server.py
- tests/seleniumwire/test_storage.py
- tests/seleniumwire/test_utils.py
> Implement in-memory request storage

- seleniumwire/server.py
- tests/seleniumwire/test_server.py
> Setting event loop here not required & breaks Django

- README.rst
- seleniumwire/request.py
- tests/end2end/test_end2end.py
- tests/seleniumwire/test_request.py
> Don't automatically decode response body

- seleniumwire/undetected_chromedriver/v2.py
> Fix exclude_hosts functionality

- seleniumwire/storage.py
- tests/seleniumwire/test_storage.py
> Handle unpickle error on request load

- seleniumwire/thirdparty/mitmproxy/net/http/encoding.py
- seleniumwire/utils.py
- setup.py
- tests/end2end/test_end2end.py
- tests/seleniumwire/test_utils.py
> Support brotli and zstd content encoding

- seleniumwire/thirdparty/mitmproxy/server/protocol/http.py
> Suppress message based on config

- seleniumwire/thirdparty/mitmproxy/net/tcp.py
- tests/end2end/test_end2end.py
> Support for socket timeouts

- seleniumwire/webdriver.py
> Fall back to pkg_resources when packaging not found

- seleniumwire/handler.py
- tests/seleniumwire/test_backend.py
> Filter out Proxy-Connection header

- README.rst
- seleniumwire/utils.py
- seleniumwire/webdriver.py
- tests/end2end/test_end2end.py
> Add ability to unset a proxy

- README.rst
- seleniumwire/server.py
- seleniumwire/utils.py
- tests/seleniumwire/test_server.py
- tests/seleniumwire/test_utils.py
> Configurable certificate path

- seleniumwire/storage.py
- tests/seleniumwire/test_storage.py
Additional fix to #369 
Improves robustness of pickled object loading.
> Handle unpickle errors

- seleniumwire/webdriver.py
> Handle missing TouchActions in Selenium 4.1.1+

- seleniumwire/handler.py
> Fix websocket interception bug

- seleniumwire/webdriver.py
> Fix compatibilty issue with Selenium 3.14.0

- seleniumwire/server.py
- tests/seleniumwire/test_server.py
> Fix behaviour of verify_ssl

- seleniumwire/thirdparty/mitmproxy/net/tls.py
- setup.py
> Drop support for SSLv2 and SSLv3

- seleniumwire/thirdparty/mitmproxy/connections.py
- seleniumwire/thirdparty/mitmproxy/server/protocol/http.py
- tests/end2end/test_end2end.py
> Fix no_proxy when using upstream SOCKS proxies
